# -*- coding: utf-8 -*-
"""Build overlay TTFs: IBM Plex Sans SC (GitHub) + device metrics (not uploaded binaries)."""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from fontTools.ttLib import TTFont

from download_ibm_plex_sc import EXTRACT_DIR, find_hinted_root
from repo_paths import FONT_STEMS, METRICS_JSON, OVERLAY_TTF_DIR, overlay_font_filename

IBM_MAP: dict[str, str] = {
    "default_medium": "IBMPlexSansSC-Medium.ttf",
    "default_semibold": "IBMPlexSansSC-SemiBold.ttf",
    "default_bold": "IBMPlexSansSC-Bold.ttf",
    "default_mono_medium": "IBMPlexSansSC-Medium.ttf",
    "default_cn_medium": "IBMPlexSansSC-Medium.ttf",
}


def load_metrics() -> dict[str, dict[str, int]]:
    data = json.loads(METRICS_JSON.read_text(encoding="utf-8"))
    return {k: v for k, v in data.items() if not k.startswith("_")}


def apply_metrics(target: Path, metrics: dict[str, int]) -> None:
    f = TTFont(target)
    h = f["hhea"]
    h.ascent = metrics["ascent"]
    h.descent = metrics["descent"]
    h.lineGap = metrics["lineGap"]
    if "OS/2" in f:
        o = f["OS/2"]
        for key in (
            "sTypoAscender",
            "sTypoDescender",
            "sTypoLineGap",
            "usWinAscent",
            "usWinDescent",
        ):
            if key in metrics:
                setattr(o, key, metrics[key])
    f.save(target)


def resolve_hinted_dir(ibm_root: Path | None) -> Path:
    if ibm_root and ibm_root.is_dir():
        return find_hinted_root(ibm_root)
    if not EXTRACT_DIR.is_dir():
        raise SystemExit("Run: python scripts/download_ibm_plex_sc.py")
    roots = [p for p in EXTRACT_DIR.iterdir() if p.is_dir()]
    base = roots[0] if len(roots) == 1 else EXTRACT_DIR
    return find_hinted_root(base)


def main() -> None:
    import argparse

    p = argparse.ArgumentParser()
    p.add_argument("--ibm-root", type=Path, default=None)
    args = p.parse_args()

    metrics_all = load_metrics()
    hinted = resolve_hinted_dir(args.ibm_root)
    OVERLAY_TTF_DIR.mkdir(parents=True, exist_ok=True)

    for old in OVERLAY_TTF_DIR.glob("*.ttf"):
        old.unlink()

    report: list[str] = []
    for stem in FONT_STEMS:
        ibm_name = IBM_MAP[stem]
        out_name = overlay_font_filename(stem)
        src = hinted / ibm_name
        if not src.is_file():
            raise SystemExit(f"Missing IBM font: {src}")
        if stem not in metrics_all:
            raise SystemExit(f"Missing metrics: {stem}")
        dst = OVERLAY_TTF_DIR / out_name
        shutil.copy2(src, dst)
        apply_metrics(dst, metrics_all[stem])
        m = metrics_all[stem]
        report.append(
            f"{out_name} <- {ibm_name} (metrics:{stem} "
            f"lh={m['ascent'] - m['descent'] + m['lineGap']})"
        )

    lic_src: Path | None = None
    for cand in [hinted, *hinted.parents]:
        c = cand / "LICENSE.txt"
        if c.is_file():
            lic_src = c
            break
    if lic_src:
        shutil.copy2(lic_src, OVERLAY_TTF_DIR / "license.txt")

    (OVERLAY_TTF_DIR / "README.txt").write_text(
        "Generated by scripts/build_overlay_fonts.py (CI/local).\n"
        "Glyphs: IBM Plex Sans SC from https://github.com/IBM/plex/releases\n"
        "Modified: vertical metrics only (see config/device-font-metrics.json).\n"
        "License: license.txt (SIL OFL 1.1)\n\n"
        + "\n".join(report)
        + "\n",
        encoding="utf-8",
    )

    print(f"Output: {OVERLAY_TTF_DIR}")
    for line in report:
        print(" ", line)


if __name__ == "__main__":
    main()
